name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Generate Docker tag
      id: docker_tag
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
          TAG_NAME="latest"
        else
          TAG_NAME=${GITHUB_REF#refs/tags/}
        fi
        echo "::set-output name=tag::$(echo "docker.pkg.github.com/${{ github.repository }}/frontend:$TAG_NAME" | awk '{print tolower($0)}')"
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.docker_tag.outputs.tag }}